# Tutorial Part 2: Arrays, Dictionaries and Reference Values

**Table of Content**

* [Isopy Arrays](#Isopy-Arrays)
    * [Creating Arrays](#Creating-Arrays)
    * [Array Attributes](#Array-Attributes)
    * [Array Methods](#Array-Methods)
    * [Array Functions](#Array-Functions)
* [Isopy Dictionaries](#Isopy-Dictionaries)
* [Reference Values](#Reference-Values)

In [1]:
import isopy
import numpy as np
import pandas as pd
import pyperclip # library for interacting with the clipboard

## Isopy Arrays
An isopy array can be seen as a table of data with a certain number of rows and columns. Each column has a key in the form of an isopy key string. These arrays allow you to easily manipulate data while keeping track of what the values represents. Technically, isopy arrays are a custom view of a structured numpy array. This means that they inherit much of the functionality of a numpy array. 

### Creating Arrays
You can create arrays directly using the ``array`` and ``asarray`` functions or by directly using the ``IsopyArray`` class. Isopy arrays can be created from a range of different data, described below.

---
When the input is a list/tuple or a numpy array we have to pass along the keys for each column in the input

In [50]:
data = [10, 20, 30] # Produces a 0-dimensional array
isopy.array(data, ['ru', 'pd', 'cd']) 

(row) , Ru , Pd , Cd 
None  , 10 , 20 , 30 

In [44]:
data = np.array([[10, 20, 30], [11, 21, 31]]) #Produces a 1-dimensional array
isopy.array(data, ['ru', 'pd', 'cd']) 

(row) , Ru , Pd , Cd 
0     , 10 , 20 , 30 
1     , 11 , 21 , 31 

**Note** The data type of each column defaults to ``numpy.float64`` for values that do not have a numpy dtype. If a value cannot be represented as a float the default data type inferred by numpy will be used. In the examples above the first array created will use the default data type while the second array will inherit the data type of the input, ``np.int32`` in this case.

---
Using the ``dtype`` keyword you can specify the data type for columns in the array. Any data type accepted by numpy is valid. You can either pass a single data type or a tuple of data types. The latter will use the first the data type which is valid for all the data in the column.

In [20]:
isopy.array([10, 20, 30], ['ru', 'pd', 'cd']).dtype # f8 stands for np.float64

dtype([('Ru', '<f8'), ('Pd', '<f8'), ('Cd', '<f8')])

In [21]:
isopy.array([10, 20, 30], ['ru', 'pd', 'cd'], dtype=np.int32).dtype # i4 stands for np.int32

dtype([('Ru', '<i4'), ('Pd', '<i4'), ('Cd', '<i4')])

In [30]:
isopy.array(['ten', 20, 30], ['ru', 'pd', 'cd'], dtype=(np.int32, str)).dtype # U stands for unicode string and the next number is the maximum length

dtype([('Ru', '<U3'), ('Pd', '<i4'), ('Cd', '<i4')])

To specify different data types for different columns pass a list of equal length to the number of columns.

In [24]:
isopy.array([10, 20, 30], ['ru', 'pd', 'cd'], dtype=[str, np.int32, np.float64]).dtype

dtype([('Ru', '<U2'), ('Pd', '<i4'), ('Cd', '<f8')])

---
Using the ``ndim`` keyword you can specify the number of dimensions of the array. To return a 0-dimensional array if possible, otherwise return a 1-dimensional array specify ``ndim`` as ``-1``. The row number of 0-dimensional arrays will appear as ``"None"`` in the ``repr()`` output of an array. You can also check the dimensionality of an array using the ``ndim`` attribute.

In [25]:
isopy.array([10, 20, 30], ['ru', 'pd', 'cd'], ndim=0) # Make 0-dimensional

(row) , Ru , Pd , Cd 
None  , 10 , 20 , 30 

In [26]:
isopy.array([10, 20, 30], ['ru', 'pd', 'cd'], ndim=1) # Make 1-dimensional

(row) , Ru , Pd , Cd 
0     , 10 , 20 , 30 

In [28]:
isopy.array([10, 20, 30], ['ru', 'pd', 'cd'], ndim=-1) # Make 0-dimesional if possible otherwise 1-dimensional.

(row) , Ru , Pd , Cd 
None  , 10 , 20 , 30 

In [27]:
isopy.array([[10, 20, 30], [11, 21, 31]], ['ru', 'pd', 'cd'], ndim = -1) 

(row) , Ru , Pd , Cd 
0     , 10 , 20 , 30 
1     , 11 , 21 , 31 

---
If the input is a dictionary or a structured numpy array the name of each column will be automatically inferred from the first argument.

In [46]:
data = dict(ru = [10, 11], pd= [20, 21], cd = [30, 31])
isopy.array(data)

(row) , Ru , Pd , Cd 
0     , 10 , 20 , 30 
1     , 11 , 21 , 31 

In [47]:
data = np.array([(10, 20, 30), (11, 21, 31)], dtype = [('ru', float), ('pd', float), ('cd', float)])
isopy.array(data)

(row) , Ru , Pd , Cd 
0     , 10 , 20 , 30 
1     , 11 , 21 , 31 

You can overwrite the inferred column keys by passing keys during creation

In [49]:
data = dict(ru = [10, 11], pd= [20, 21], cd = [30, 31])
isopy.array(data, ['101ru', '105pd', '111cd'])

(row) , 101Ru , 105Pd , 111Cd 
0     , 10    , 20    , 30    
1     , 11    , 21    , 31    

You can convert an isopy array back into a numpy array or a dictionary using the ``to_ndarray()`` and ``to_dict()`` methods.

---
There are a number of methods for converting isopy arrays into other python objects

In [19]:
a = isopy.array(dict(ru = [10, 11], pd= [20, 21], cd = [30, 31]))
a.to_ndarray() # Converts array into a structured numpy array

array([(10., 20., 30.), (11., 21., 31.)],
      dtype=[('Ru', '<f8'), ('Pd', '<f8'), ('Cd', '<f8')])

In [20]:
a.to_dict() # Converts array into a dictionary

{'Ru': [10.0, 11.0], 'Pd': [20.0, 21.0], 'Cd': [30.0, 31.0]}

---
Similarly you can create isopy arrays from a pandas dataframe

In [2]:
df = pd.DataFrame(dict(ru = [10, 11], pd= [20, 21], cd = [30, 31]))
df

ru  pd  cd
0  10  20  30
1  11  21  31

In [3]:
isopy.array(df)

(row) , Ru , Pd , Cd 
0     , 10 , 20 , 30 
1     , 11 , 21 , 31 

You can convert a isopy array back into a dataframe using the ``to_dataframe()`` method or by passing it directly to ``DataFrame()``

In [4]:
array = isopy.array(df)
array.to_dataframe()

Ru  Pd  Cd
0  10  20  30
1  11  21  31

In [5]:
pd.DataFrame(array)

Ru  Pd  Cd
0  10  20  30
1  11  21  31

---
You can create arrays from existing isopy arrays

In [57]:
a = isopy.array([10, 20, 30], ['ru', 'pd', 'cd']) 
isopy.array(a)

(row) , Ru , Pd , Cd 
None  , 10 , 20 , 30 

There key difference between ``array`` and ``asarray`` is that if the first argument is an isopy array then  ``asarray`` will return a reference that array, rather than a copy, if no other arguments are given while ``array`` will return a copy.

In [2]:
a = isopy.array([10, 20, 30], ['ru', 'pd', 'cd']) 
isopy.array(a) is a, isopy.asarray(a) is a

(False, True)

#### Filled Arrays
You can create an array of uninitiated values, zeros or ones using the ``empty``, ``zeros`` and ``one`` functions.

In [17]:
isopy.empty(None, ['ru', 'pd', 'cd']) #None, or -1, creates a 0-dimensional array

(row) , Ru , Pd          , Cd 
None  , 0  , 8.2859e-312 , -0 

In [19]:
isopy.zeros(1, ['ru', 'pd', 'cd'])

(row) , Ru , Pd , Cd 
0     , 0  , 0  , 0  

In [65]:
isopy.ones(2, ['ru', 'pd', 'cd'])

(row) , Ru , Pd , Cd 
0     , 1  , 1  , 1  
1     , 1  , 1  , 1  

To create an array filled with a specific value use the ``full`` function. The second arguement is the fill value. This can either be a single value used for all rows in the column or a sequence of values of of the same length as the number of rows.

In [6]:
isopy.full(2, np.nan, ['ru', 'pd', 'cd'])

(row) , Ru  , Pd  , Cd  
0     , nan , nan , nan 
1     , nan , nan , nan 

In [5]:
isopy.full(2, [1,2], ['ru', 'pd', 'cd'])

(row) , Ru , Pd , Cd 
0     , 1  , 1  , 1  
1     , 2  , 2  , 2  

---
If no keys are given, or can be inferred, a normal numpy array is returned.

In [3]:
isopy.ones(5) # same as np.ones(5)

array([1., 1., 1., 1., 1.])

---
#### Random Arrays
To create an array of random values use the ``random`` function. The second argument is either a single argument or a tuple of arguments that will be passed to the random generator. By default this function draws values from a normal distribution. The following example draws values from a normal distribution with a center of 1 and standard deviation of 0.1

In [12]:
isopy.random(10, (1, 0.1), ['ru', 'pd', 'cd'])

(row) , Ru      , Pd      , Cd      
0     , 0.96959 , 1.0281  , 0.79312 
1     , 0.95192 , 1.0449  , 1.0856  
2     , 1.0982  , 0.97543 , 0.94024 
3     , 1.0573  , 0.9973  , 0.8874  
4     , 0.94976 , 1.019   , 0.78627 
5     , 1.099   , 0.99962 , 1.0155  
6     , 1.1471  , 0.86524 , 1.0227  
7     , 1.0914  , 1.0253  , 0.93167 
8     , 1.0465  , 0.90448 , 0.94372 
9     , 0.91533 , 0.95526 , 0.99472 

You can specify different distributions for different columns by passing a list as the second argument

In [13]:
isopy.random(10, [(1, 0.1), (0,1), (10, 1)], ['ru', 'pd', 'cd'])

(row) , Ru      , Pd       , Cd     
0     , 1.0187  , 2.4206   , 11.091 
1     , 1.1119  , -1.0512  , 9.2026 
2     , 0.92309 , 0.26226  , 10.231 
3     , 1.0747  , 0.31492  , 10.051 
4     , 0.89444 , 1.4324   , 10.175 
5     , 0.87109 , 0.68955  , 9.2957 
6     , 1.0984  , -0.70649 , 10.48  
7     , 1.2338  , 0.40023  , 10.142 
8     , 1.0538  , 1.0639   , 10.11  
9     , 0.9434  , -0.50517 , 10.73  

---
If no keys are given, or can be inferred, a normal numpy array is returned.

In [4]:
isopy.random(10)

array([-0.66929881, -0.66053013,  0.93081883, -1.07150801, -0.23177742,
       -0.93340998, -0.58119726, -0.45745434, -0.30148965,  1.02422904])

### Array Attributes
Since isopy arrays are custom implementation of a numpy arrays they have all the attributes you would find in numpy arrays, e.g. ``size``, ``.ndim``, ``.shape`` and ``.dtype``.

In [35]:
a = isopy.array(dict(ru = [10, 11], pd= [20, 21], cd = [30, 31]))
a.size, a.ndim, a.shape, a.dtype

(2, 1, (2,), dtype([('Ru', '<f8'), ('Pd', '<f8'), ('Cd', '<f8')]))

In addition to the numpy attributes ``.nrows`` and ``.ncols`` are also available for isopy arrays. There return the number of rows and number of columns in the array respectively.

In [36]:
a.nrows, a.ncols

(2, 3)

**Note** That ``.size`` will return ``1`` for both 0-dimensional arrays and 1-dimensional arrays with 1 row.  ``.nrows`` on the other hand will return ``-1`` 0-dimensional arrays.

In [5]:
a = isopy.array(dict(ru = 10, pd= 20, cd = 30))
a.size, a.nrows

(1, -1)

The column keys are available through the ``.keys`` attribute

In [38]:
a.keys # a.keys() also works fine

ElementKeyList('Ru', 'Pd', 'Cd')

### Array Methods
While isopy arrays also contain all the methods found in numpy arrays many of these are not relevant to isopy arrays and may therefore not work as expected, if at all. See the reference documentation for a list of all methods that have been implemented for isopy arrays. Any methods not listed there should be used with **caution** as the behavior is undefined.

---
Isopy arrays have a number of methods that mimic those found in dictionaries. In addition to the ``.keys`` attribute, that can be used as a method, arrays also have ``values()``, ``items()`` and ``get()`` methods.

In [6]:
a = isopy.array(dict(ru = [10, 11], pd= [20, 21], cd = [30, 31]))
a.values()

(array([10., 11.]), array([20., 21.]), array([30., 31.]))

In [7]:
a.items()

((ElementKeyString('Ru'), array([10., 11.])),
 (ElementKeyString('Pd'), array([20., 21.])),
 (ElementKeyString('Cd'), array([30., 31.])))

**Note** both``values()`` and ``items()`` both return a tuple (Unlike dictionaries where they return iterators). 

In [45]:
a.get('ru')

array([10., 11.])

If a column with the specified key is not present in the array a default value is return with the same shape as a column in the array.

In [46]:
a.get('ag') # If not specified the default value is np.nan

array([nan, nan])

In [48]:
a.get('ag', 40) # Second argument is the default value

array([40, 40])

In [50]:
a.get('ag', [40, 41]) # A sequence the same shape as a valid column is also accepted

array([40, 41])

---
The ``filter()`` method return a view containing only the columns that match the supplied key filters. See the ``filter()`` method for the different key lists for available filter keywords.

In [7]:
a = isopy.array(dict(ru101 = [10, 11], pd105= [20, 21], cd111 = [30, 31]))
a.filter(mass_number_gt=104) # Return only the columns with that have a mass number greater than 104

(row) , 105Pd , 111Cd 
0     , 20    , 30    
1     , 21    , 31    

---
The ``copy()`` method can be used to return a copy of the array

In [3]:
a = isopy.array(dict(ru101 = [10, 11], pd105= [20, 21], cd111 = [30, 31]))
b = a.copy()
b is a, a == b

(False, True)

You can copy only those columns that meet a certain criteria by passing filter keywords as in the ``filter()`` method described above.

In [4]:
a = isopy.array(dict(ru101 = [10, 11], pd105= [20, 21], cd111 = [30, 31]))
a.copy(mass_number_gt = 104) # Return only the columns with that have a mass number greater than 104

(row) , 105Pd , 111Cd 
0     , 20    , 30    
1     , 21    , 31    

---
You can create a ratio from data within an array using the ``ratio()`` method

In [4]:
c = a.ratio('105Pd'); c

(row) , 101Ru/105Pd , 111Cd/105Pd 
0     , 0.5         , 1.5         
1     , 0.52381     , 1.4762      

Ratio arrays have a ``deratio()`` method for flattening a ratio array. This requires that all column keys in the array have a common denominator

In [5]:
c.deratio()

(row) , 101Ru   , 111Cd  , 105Pd 
0     , 0.5     , 1.5    , 1     
1     , 0.52381 , 1.4762 , 1     

In [7]:
c.deratio([20, 21]) #You can specify the value(s) for the denominator

(row) , 101Ru , 111Cd , 105Pd 
0     , 10    , 30    , 20    
1     , 11    , 31    , 21    

---
The  ``normalise`` function allows you to normalise the data in the array to a certian value. Calling the function without any arguments will normalise all the values to that the sum of each row is ``1``

In [10]:
a = isopy.array(dict(ru = [10, 11], pd= [20, 21], cd = [30, 31]))
a.normalise()

(row) , Ru      , Pd      , Cd      
0     , 0.16667 , 0.33333 , 0.5     
1     , 0.1746  , 0.33333 , 0.49206 

The optional arguments are 1) the value you with to normalise to and 2) the key(s) of the columns that the normalisation should be based on.

In [11]:
a.normalise(100, 'pd')

(row) , Ru     , Pd  , Cd     
0     , 50     , 100 , 150    
1     , 52.381 , 100 , 147.62 

In [19]:
a.normalise([100, 1000], ['ru', 'cd']) # The sum of the specified keys will be equal to the values given

(row) , Ru    , Pd  , Cd    
0     , 25    , 50  , 75    
1     , 261.9 , 500 , 738.1 

In [16]:
a.normalise([100, 1000], ['ru', 'cd']).normalise([20, 21], 'pd')

(row) , Ru , Pd , Cd 
0     , 10 , 20 , 30 
1     , 11 , 21 , 31 

---
With the ``to_text()`` method of arrays you can convert the contents of an array to a text string. The ``str()`` ``repr()`` functions both call this function to produce two slightly different strings. The *str* function will return the raw data in each column of the array.

In [6]:
array = isopy.random(20, keys='ru pd cd'.split())

In [7]:
print(array) # Same as print( str(array) ) and print( array.to_text() )

Ru                    , Pd                     , Cd                    
-1.5346520665946386   , 0.04779323735332215    , -0.38608690429742065  
0.6258243797981192    , 0.31615074992666947    , -0.39506655781061456  
1.116256444664327     , -1.4036071734639097    , -0.8346316435798058   
1.2121879004881462    , 0.19130544609119915    , 0.7336370728715296    
0.6851269628625932    , -1.2958798551969863    , -0.16428641685441137  
-1.3255067317327287   , -0.9955201366005855    , -0.00536694806898058  
-2.5011786482220892   , 1.1338474420244922     , 0.5352426048567351    
1.5837930282297807    , -0.19571571691158882   , 1.0857862368500883    
-0.8579325126803901   , 1.4787118005182744     , -0.31632889493541405  
-0.6132487494907979   , -0.0031489928659609078 , 0.7935620185881183    
0.10379625092198584   , -0.9125627929294656    , 0.010980333987966722  
-1.0904534442766558   , 0.05335642471310984    , 0.30230916508920563   
-0.006671411922914303 , 0.36955711039412475    , -0.040057435798

The *repr* function will format *float* values to 5 significant digits, include an additional column with the row number, and it will only show a maximum of 10 rows.

In [8]:
array # Same as print( repr(array) ) and print( array.to_text(nrows = 10, include_row=True, f='{:.5g}') )

(row) , Ru      , Pd        , Cd       
0     , -1.5347 , 0.047793  , -0.38609 
1     , 0.62582 , 0.31615   , -0.39507 
2     , 1.1163  , -1.4036   , -0.83463 
3     , 1.2122  , 0.19131   , 0.73364  
4     , 0.68513 , -1.2959   , -0.16429 
...   , ...     , ...       , ...      
15    , 1.2091  , -0.047916 , -0.42337 
16    , 2.3386  , 0.94192   , 1.1487   
17    , 1.554   , 0.79286   , -0.45725 
18    , 0.23261 , -0.19106  , -0.60498 
19    , 1.1719  , 0.13397   , -0.12066 

There are a number of optional arguments you can specify to change things like number formats and the delimiter for the string

In [10]:
print( array.to_text(delimiter = '\t', include_row=True) ) #includes the row number and uses a tab delimiter

(row) 	Ru                    	Pd                     	Cd                    
0     	-1.5346520665946386   	0.04779323735332215    	-0.38608690429742065  
1     	0.6258243797981192    	0.31615074992666947    	-0.39506655781061456  
2     	1.116256444664327     	-1.4036071734639097    	-0.8346316435798058   
3     	1.2121879004881462    	0.19130544609119915    	0.7336370728715296    
4     	0.6851269628625932    	-1.2958798551969863    	-0.16428641685441137  
5     	-1.3255067317327287   	-0.9955201366005855    	-0.00536694806898058  
6     	-2.5011786482220892   	1.1338474420244922     	0.5352426048567351    
7     	1.5837930282297807    	-0.19571571691158882   	1.0857862368500883    
8     	-0.8579325126803901   	1.4787118005182744     	-0.31632889493541405  
9     	-0.6132487494907979   	-0.0031489928659609078 	0.7935620185881183    
10    	0.10379625092198584   	-0.9125627929294656    	0.010980333987966722  
11    	-1.0904534442766558   	0.05335642471310984    	0.30230916508920563   

If you are using jupyter you can use the ``display_table()`` method to render a nice table in a cell. Except from *delimiter* it takes the same arguments as ``to_text()``

In [11]:
array.display_table(include_row=True)

(row) | Ru                    | Pd                     | Cd                    
------| ---------------------:| ----------------------:| ---------------------:
0     | -1.5346520665946386   | 0.04779323735332215    | -0.38608690429742065  
1     | 0.6258243797981192    | 0.31615074992666947    | -0.39506655781061456  
2     | 1.116256444664327     | -1.4036071734639097    | -0.8346316435798058   
3     | 1.2121879004881462    | 0.19130544609119915    | 0.7336370728715296    
4     | 0.6851269628625932    | -1.2958798551969863    | -0.16428641685441137  
5     | -1.3255067317327287   | -0.9955201366005855    | -0.00536694806898058  
6     | -2.5011786482220892   | 1.1338474420244922     | 0.5352426048567351    
7     | 1.5837930282297807    | -0.19571571691158882   | 1.0857862368500883    
8     | -0.8579325126803901   | 1.4787118005182744     | -0.31632889493541405  
9     | -0.6132487494907979   | -0.0031489928659609078 | 0.7935620185881183    
10    | 0.10379625092198584   | -0.9125627929294656    | 0.010980333987966722  
11    | -1.0904534442766558   | 0.05335642471310984    | 0.30230916508920563   
12    | -0.006671411922914303 | 0.36955711039412475    | -0.040057435798353455 
13    | -0.8001002756075178   | -0.6572436015937474    | 0.280739539634643     
14    | -0.7184102215640251   | -1.7477356662737502    | 1.0657115291679098    
15    | 1.2091091171897914    | -0.047916289860762656  | -0.4233700617727204   
16    | 2.3386043705766033    | 0.9419163369651208     | 1.1486965167330558    
17    | 1.554033197131996     | 0.7928642151004565     | -0.4572469728413151   
18    | 0.23261221391623185   | -0.19105561037213234   | -0.6049752275512749   
19    | 1.1718743488371184    | 0.13396573912684853    | -0.1206567731332395   

### Array Functions
An array function is a function that perform an action on one or more arrays, e.g. adding arrays together or finding the mean of values in an array.

The isopy package comes with several custom made array functions and isopy arrays support a large number of the numpy array functions. The tested numpy array functions are included in the isopy namespace. See [Introduction Part 3: Working with arrays]() **LINK MISSING** for a comprehensive explanation of array functions with lots examples.

A few quick examples are

In [2]:
a1 = isopy.array(dict(ru = 1, pd= 2, cd = 3))
a2 = isopy.array(dict(ru = 10, pd= 20, ag = 25))
a1 + a2 # Columns not present in all arrays are assinged a value of np.nan

(row) , Ru , Pd , Cd  , Ag  
None  , 11 , 22 , nan , nan 

In [13]:
a = isopy.random(100, [(1, 0.1), (0, 1), (10, 2)], ['ru', 'pd', 'cd'])
isopy.mean(a) #Calculate the mean of each column

(row) , Ru     , Pd       , Cd     
None  , 1.0004 , -0.06699 , 10.331 

In [14]:
isopy.std(a) # Calculate the standard deviation of each column

(row) , Ru      , Pd      , Cd     
None  , 0.11547 , 0.96741 , 1.9885 

---
One useful feature of the array function implementation for isopy arrays is that they can be used in conjunction with dictionaries. Only keys present in the array are included in the output meaning the dictionary can contain as many keys as you want. Thus dictionaries are useful for storing reference values.

In [2]:
a = isopy.array(dict(ru = 10, pd= 20, cd = 30))
d = dict(ru = 1, rh = 2, pd=3, ag=4, cd = 5)
a + d # Only column keys in the array are present in the output

(row) , Ru , Pd , Cd 
None  , 11 , 23 , 35 

**Note** The dictionary keys do not need to formatted to match the proper key string format.

## Isopy Dictionaries

Isopy has two special dictionaries, ``IsopyDict`` and ``ScalarDict``. These function much like normal dictionaries with a few enhancements. First, all values are stored as isopy key strings. Second, they can be readonly and have predefined default values. Third, you can create a subsection of the dictionary using ``copy()`` by passing filter keywords.

In [12]:
d = isopy.IsopyDict(ru101 = 1, rh103 = 2, pd105=3, ag107=4, cd111 = 5, default_value=0); d # The input can also be a another dictionary

IsopyDict(default_value = 0, readonly = False,
{"101Ru": 1
"103Rh": 2
"105Pd": 3
"107Ag": 4
"111Cd": 5})

In [14]:
d.get('76ge'), d.get('80se', 100) # If not specified the default value of the dictionary is used

(0, 100)

In [16]:
d = isopy.IsopyDict(ru101 = 1, rh103 = 2, pd105=3, ag107=4, cd111 = 5, default_value=0)
d.copy(mass_number_gt = 104) # Returns a new dict containing only isotopes with a mass number greater than 104

IsopyDict(default_value = 0, readonly = False,
{"105Pd": 3
"107Ag": 4
"111Cd": 5})

---
``ScalarDict`` works just like an ``IsopyDict`` with three exceptions. First it can only store float values and each value in the dictionary must have the same size. Second, the ``get()`` method can calculate the ratio of two values in the dictionary if a ratio key string is not present in the dictionary. Finally, you can create an array directly from the dictionary with the ``to_array()`` method.

In [3]:
d = isopy.ScalarDict(ru101 = 1, rh103 = 2, pd105=3, ag107=4, cd111 = 5) # Default value is by default np.nan
d.get('pd105/cd111') # Automatically calculated from the numerator and denominator values

0.6

In [4]:
d.to_array()

(row) , 101Ru , 103Rh , 105Pd , 107Ag , 111Cd 
None  , 1     , 2     , 3     , 4     , 5     

In [5]:
d.to_array(mass_number_gt = 104) # You can specify key filters too

(row) , 105Pd , 107Ag , 111Cd 
None  , 3     , 4     , 5     

## Reference Values
There are a number of reference values included with isopy under the ``refval`` namespace. You can find the available reference values listed [here](https://isopy.readthedocs.io/en/latest/refpages/reference_values.html) toghether with a short description. There are currently three categories of reference values, ``mass``, ``element`` and ``isotope`` referring to the flavour of the key string of the values in the dictionaries. 

In [6]:
isopy.refval.element.atomic_number.get('pd') # The atomic number of palladium

46

In [7]:
isopy.refval.isotope.fraction.get('105pd') # The natural isotope fraction of 105Pd

0.2233

In [8]:
isopy.refval.element.isotopes.get('pd') # Returns a list of all naturally occuring isotopes of palladium

IsotopeKeyList('102Pd', '104Pd', '105Pd', '106Pd', '108Pd', '110Pd')

---
Many reference values are isopy dictionaries so the ``copy()`` method accepts filter keywords

In [9]:
isopy.refval.isotope.fraction.copy(element_symbol='pd')

ScalarDict((default_value = nan, readonly = False,
key_flavours = ('mass', 'element', 'isotope', 'ratio', 'mixed', 'molecule', 'general'),
{"102Pd": 0.0102
"104Pd": 0.1114
"105Pd": 0.2233
"106Pd": 0.2733
"108Pd": 0.2646
"110Pd": 0.1172})

Similarly many reference values has the ``to_array()`` method.

In [10]:
isopy.refval.isotope.fraction.to_array(element_symbol='pd')

(row) , 102Pd  , 104Pd  , 105Pd  , 106Pd  , 108Pd  , 110Pd  
None  , 0.0102 , 0.1114 , 0.2233 , 0.2733 , 0.2646 , 0.1172 